/**
 * RL Lab trained-agent GIFs (repo README) baked into JPEG FILMSTRIPS:
 * 10 frames side by side, 240px each; the dev scene plays them on
 * the ambient clock (frame 0 shows under reduced motion).
 *
 * The filmstrips were generated by `node local/tmp/gen-devanims.mjs` and
 * now live as REAL files in ./img, imported as Vite assets (hashed,
 * immutable-cached) — the former base64 payloads cost the CanvasStage
 * chunk ~155 KB of JS parse/eval on every load (perf pass 2026-07-14).
 * The dev scene still decodes them lazily (draws skip until complete).
 */

import lunarlanderUrl from './img/lunarlander.jpg'
import breakoutUrl from './img/breakout.jpg'

export const DEV_ANIMS: Record<string, { url: string; frames: number; fw: number; fh: number }> = {
  lunarlander: {
    url: lunarlanderUrl,
    frames: 10,
    fw: 240,
    fh: 178,
  },
  breakout: {
    url: breakoutUrl,
    frames: 10,
    fw: 240,
    fh: 328,
  },
}
