/**
 * GENERATED by `node local/tmp/gen-projectshots.mjs` — do not edit.
 * Real screenshots of Martin's projects, one ARRAY per card (images stack
 * vertically in the Work panel). Stills are 760px JPEGs served from
 * public/shots/ (loaded lazily per card); heavy animations ride as public/
 * URLs too (the RL Lab taxi GIF, the contact-scene nebula mp4). Keys with a
 * `.cs` suffix are the Czech-language variant; the panel falls back to the
 * plain id. Projects with no entry render as a clean text card.
 */

export type ProjectShot = {
  url: string
  aspect: number
  /** True when the image is a book cover, not a screenshot — the alt text
   *  says so instead of calling it a screenshot. */
  cover?: boolean
}

export const PROJECT_SHOTS: Record<string, ProjectShot[]> = {
  'moje-cesta': [
    { url: '/shots/moje-cesta-0.jpg', aspect: 1.000 },
  ],
  'rrcentrum': [
    { url: '/shots/rrcentrum-0.jpg', aspect: 2.426 },
    { url: '/shots/rrcentrum-1.jpg', aspect: 1.916 },
  ],
  'bitcoin-article': [
    { url: '/shots/bitcoin-article-0.jpg', aspect: 1.890 },
  ],
  'clearfeed': [
    { url: '/shots/clearfeed-0.jpg', aspect: 2.500 },
  ],
  // Not a screenshot — the book's own cover, taken from the repo README
  // (`book/cover.png`, 2000×3200) and baked to the same 760px JPEG as the rest.
  // Cropped to its lower band (the last anomaly marker, the rule, the title):
  // the full portrait cover made a card twice as tall as every other one.
  'unplottable': [
    { url: '/shots/unplottable-0.jpg', aspect: 1.250, cover: true },
  ],
  // The page itself: the verdict, the eight-hour strip with the showers coming
  // in, and both dials — the radar calm, the forecasts at 66. One image, not
  // two: the radar map that used to sit under it doubled the card's height and
  // out-shouted the product. Baked by `local/tmp/bourky-bake.mjs`, which feeds
  // the page a scenario from the project's own test suite so the shot shows
  // what the app is FOR (a real calm day is an empty blue strip).
  'bourky': [
    { url: '/shots/bourky-0.jpg', aspect: 1.143 },
  ],
  // The book's own generated cover (`book/cover.png`, 1600×2560), cropped to
  // the band that carries its identity — the title block and the red stitch
  // seam — for the same reason Unplottable is cropped: the full portrait page
  // makes a card twice as tall as every other one. Baked by
  // `local/tmp/den-cover-bake.mjs`.
  'den-ktery-se-nestal': [
    { url: '/shots/den-ktery-se-nestal-0.jpg', aspect: 1.250, cover: true },
  ],
  'tenovice': [
    { url: '/shots/tenovice-0.jpg', aspect: 0.983 },
  ],
  'tenovice.cs': [
    { url: '/shots/tenovice_cs-0.jpg', aspect: 0.986 },
  ],
  'registrace': [
    { url: '/shots/registrace-0.jpg', aspect: 1.600 },
  ],
  'registrace.cs': [
    { url: '/shots/registrace_cs-0.jpg', aspect: 1.585 },
  ],
  'brainquest': [
    { url: '/shots/brainquest-0.jpg', aspect: 1.014 },
  ],
  'due-deck': [
    { url: '/shots/due-deck-0.jpg', aspect: 1.359 },
  ],
  'due-deck.cs': [
    { url: '/shots/due-deck_cs-0.jpg', aspect: 1.368 },
  ],
  'rand-pulse': [
    { url: '/shots/rand-pulse-0.jpg', aspect: 1.685 },
  ],
  'strc-check': [
    { url: '/shots/strc-check-0.jpg', aspect: 1.488 },
  ],
  'wealth-deck': [
    { url: '/shots/wealth-deck-0.jpg', aspect: 1.072 },
  ],
  'wealth-deck.cs': [
    { url: '/shots/wealth-deck_cs-0.jpg', aspect: 1.059 },
  ],
  'this-site': [
    { url: '/shots/this-site-0.jpg', aspect: 2.062 },
    { url: '/contact-nebula.mp4', aspect: 1.798 },
  ],
  'this-site.cs': [
    { url: '/shots/this-site_cs-0.jpg', aspect: 2.094 },
    { url: '/contact-nebula.mp4', aspect: 1.798 },
  ],
  'rl-lab': [
    { url: '/shots/rl-lab-0.jpg', aspect: 2.857 },
    { url: '/rl-lab-taxi.mp4', aspect: 1.579 },
  ],
}
