/**
 * GENERATED by `node local/tmp/gen-projectshots.mjs` — do not edit.
 * Real screenshots of Martin's projects, one ARRAY per card (images stack
 * vertically in the Work panel). Stills are 760px JPEGs served from
 * public/shots/ (loaded lazily per card); heavy animations ride as public/
 * URLs too (the RL Lab taxi GIF, the contact-scene nebula mp4). Keys with a
 * `.cs` suffix are the Czech-language variant; the panel falls back to the
 * plain id. Projects with no entry render as a clean text card.
 */

export type ProjectShot = { url: string; aspect: number }

export const PROJECT_SHOTS: Record<string, ProjectShot[]> = {
  'moje-cesta': [
    { url: '/shots/moje-cesta-0.jpg', aspect: 1.000 },
  ],
  'rrcentrum': [
    { url: '/shots/rrcentrum-0.jpg', aspect: 2.426 },
    { url: '/shots/rrcentrum-1.jpg', aspect: 1.916 },
  ],
  'bitcoin-article': [
    { url: '/shots/bitcoin-article-0.jpg', aspect: 1.890 },
  ],
  'clearfeed': [
    { url: '/shots/clearfeed-0.jpg', aspect: 2.500 },
  ],
  'tenovice': [
    { url: '/shots/tenovice-0.jpg', aspect: 1.074 },
  ],
  'tenovice.cs': [
    { url: '/shots/tenovice_cs-0.jpg', aspect: 0.986 },
  ],
  'registrace': [
    { url: '/shots/registrace-0.jpg', aspect: 1.600 },
  ],
  'registrace.cs': [
    { url: '/shots/registrace_cs-0.jpg', aspect: 1.585 },
  ],
  'brainquest': [
    { url: '/shots/brainquest-0.jpg', aspect: 1.014 },
  ],
  'due-deck': [
    { url: '/shots/due-deck-0.jpg', aspect: 1.359 },
  ],
  'due-deck.cs': [
    { url: '/shots/due-deck_cs-0.jpg', aspect: 1.368 },
  ],
  'rand-pulse': [
    { url: '/shots/rand-pulse-0.jpg', aspect: 1.685 },
  ],
  'strc-check': [
    { url: '/shots/strc-check-0.jpg', aspect: 1.488 },
  ],
  'wealth-deck': [
    { url: '/shots/wealth-deck-0.jpg', aspect: 1.072 },
  ],
  'wealth-deck.cs': [
    { url: '/shots/wealth-deck_cs-0.jpg', aspect: 1.059 },
  ],
  'this-site': [
    { url: '/shots/this-site-0.jpg', aspect: 2.062 },
    { url: '/contact-nebula.mp4', aspect: 1.798 },
  ],
  'this-site.cs': [
    { url: '/shots/this-site_cs-0.jpg', aspect: 2.094 },
    { url: '/contact-nebula.mp4', aspect: 1.798 },
  ],
  'rl-lab': [
    { url: '/shots/rl-lab-0.jpg', aspect: 2.857 },
    { url: '/rl-lab-taxi.gif', aspect: 1.579 },
  ],
}
